import os

LOCALIZATION = {
    "en": {
        "app_title": "ComfyUI XMP Tagger",
        "header_title": "📷 ComfyUI PNG Metadata -> DigiKam XMP Tagger",
        "header_subtitle": "Automatically converts ComfyUI workflows into hierarchical XMP tags",
        "scan_dir_label": "Directory:",
        "scan_dir_placeholder": "Select a folder containing ComfyUI PNG images...",
        "btn_browse": "Browse...",
        "btn_next_folder": "⏭ Next Folder",
        "btn_scan": "Scan Folder",
        "lbl_sec_categories_prefixes": "📌 Tag Categories & Prefixes",
        "lbl_sec_categories_prefixes_tooltip": "Choose which categories to capture from ComfyUI metadata.\nThe prefixes define the folder structure in digiKam (e.g., 'Model/juggernaut').",
        "lbl_prefix_short": "Prefix:",
        "tab_tagger_options": "Tagger Options",
        "tab_metadata_selection": "Metadata Selection",
        "tab_layout_design": "Layout & Design",
        "lbl_categories": "Tracked Categories",
        "chk_include_models": "Capture model names (Checkpoints)",
        "chk_include_loras": "Capture LoRA names",
        "chk_include_samplers": "Capture Sampler / Scheduler",
        "chk_include_prompts": "Capture prompt keywords (running text)",
        "chk_write_flat_dc": "Write flat keywords (dc:subject)",
        "chk_ignore_inactive_nodes": "Ignore inactive/muted nodes",
        "chk_ignore_numeric_tags": "Exclude pure numbers (e.g. seed, cfg)",
        "chk_lowercase_prompt_tags": "Normalize prompt tags to lowercase (avoids duplicates e.g. \"Portrait\" / \"portrait\")",
        "chk_recursive_scan": "Recursive",
        "chk_recursive_scan_tooltip": "When enabled, search and scan for PNG images in all subfolders of the selected directory.",
        "lbl_sec_resolution_tiers": "📐 Megapixel Tiers (Resolution Tags)",
        "lbl_sec_resolution_tiers_tooltip": "Generates tags based on the megapixel size of the image.\nUseful to mark previews, standard images, and upscaled images.",
        "lbl_res_tier1_desc": "Tier 1 (Preview): <",
        "lbl_res_tier2_desc": "Tier 2 (Standard): <",
        "lbl_res_tier3_desc": "Tier 3 (Upscale): >=",
        "lbl_res_tier2_mp_arrow": "Tier 2 MP ->",
        "lbl_sec_active_lora_filter": "🎯 Active LoRA & Node Filter",
        "lbl_sec_active_lora_filter_tooltip": "Nodes that were muted or bypassed in ComfyUI can be ignored.\nLoRAs below the minimum strength will not be captured.",
        "lbl_sec_whitelist": "✅ Whitelist (Positives)",
        "lbl_sec_whitelist_tooltip": "When the Whitelist is active, only tags that exactly match or partially contain\nitems in this list will be processed and saved. All other extracted tags are discarded.\n\nEnter comma-separated tags here, or click the link below to edit the\n'whitelist.txt' file directly. This is useful for restricting tags to\na specific vocabulary (e.g. for Danbooru/DigiKam projects).",
        "lbl_sec_blacklist": "🚫 Blacklist (Ignore keywords)",
        "lbl_sec_blacklist_tooltip": "Global filter controls: Items in this list are completely discarded from all parsed metadata fields (prompts, checkpoints, LoRAs, samplers, etc.).\n- Blacklist: Discards matching words/phrases (comma-separated).\n- Exclude pure numbers: Ignores numerical tags (like seed values).\n- Normalize to lowercase: Converts prompt tags to lowercase to prevent duplicates.\n- Word-based tagging (Stopwords/Adjectives): Splits prompts into individual words and filters them using stopword lists, adjective compound rules, or minimum length thresholds.",
        "chk_overwrite_existing_tags": "Overwrite XMP tags (instead of appending)",
        "chk_word_based_tagging": "Split prompts into single words (Word-based)",
        "lbl_edit_stopwords": "📄 Edit fill words list (stopwords.txt)",
        "lbl_edit_adjectives": "📄 Edit adjectives list (adjectives.txt)",
        "lbl_edit_short_words": "📄 Edit short-word exceptions list (short_words.txt)",
        "lbl_edit_whitelist": "📄 Edit whitelist file (whitelist.txt)",
        "lbl_edit_blacklist": "📄 Edit blacklist file (blacklist.txt)",
        "lbl_resolution_settings": "📐 Image Size & Resolution Tags",
        "chk_include_resolution": "Generate resolution tags (MP tiers)",
        "lbl_res_prefix": "Prefix for resolution tag:",
        "lbl_res_tier1": "Tier 1 (e.g. Preview) MP limit:",
        "lbl_res_tier1_name": "Name:",
        "lbl_res_tier2": "Tier 2 (e.g. Standard) MP limit:",
        "lbl_res_tier3_name": "Tier 3 (e.g. Upscale) Name:",
        "lbl_tag_prefixes": "🏷 Prefixes in hierarchical structure",
        "lbl_prefix_model": "Model prefix:",
        "lbl_prefix_lora": "LoRA prefix:",
        "lbl_prefix_sampler": "Sampler prefix:",
        "lbl_prefix_prompt": "Prompt prefix:",
        "lbl_min_lora_strength": "Minimum strength for LoRA capture:",
        "lbl_max_tag_length": "Maximum tag length (characters):",
        "lbl_whitelist_settings": "✅ Whitelist (Only capture these tags)",
        "chk_use_whitelist": "Only allow keywords from the whitelist",
        "lbl_whitelist_tags": "Tags (comma-separated):",
        "lbl_blacklist_settings": "🚫 Blacklist (Ignore these keywords)",
        "lbl_blacklist_tags": "Tags (comma-separated):",
        "lbl_custom_prompt_keys": "🔑 Custom Prompt Field Names (Workflow keys)",
        "lbl_sec_custom_prompt_keys": "🔑 Custom Prompt Field Names (Workflow keys)",
        "lbl_sec_custom_prompt_keys_tooltip": "Enter custom Node IDs or widget names that contain prompt text (one per line).\nThe parser will search the workflow JSON for these specific identifiers\nto extract prompt text, enabling support for specialized loader nodes\nor custom workflow structures.",
        "lbl_storage_mode": "💾 Storage Mode",
        "lbl_sec_storage_mode": "💾 Storage & Process Options",
        "lbl_sec_storage_mode_tooltip": "Configure metadata storage targets and tagging confirmation dialogs.",
        "chk_show_tagging_confirm": "Show confirmation dialog before writing XMP tags",
        "chk_show_tagging_confirm_tooltip": "When enabled, prompts you to confirm before applying tags to files.",
        "lbl_storage_mode_desc": "How should XMP metadata be stored?",
        "rad_storage_embed": "Embed directly in PNG file (Recommended)",
        "rad_storage_sidecar": "Write as XMP sidecar file (.png.xmp)",
        "chk_write_created_date": "Write creation date (xmp:CreateDate)",
        "chk_write_camera_model": "Write camera model (tiff:Model)",
        "chk_write_description": "Write description (dc:description)",
        "lbl_custom_fields": "✍ Global Metadata Values",
        "lbl_sec_extra_meta": "✍ Global Metadata Values",
        "lbl_sec_extra_meta_tooltip": "Configure static metadata fields (Creator, Copyright, Camera Make, etc.)\nto be injected into every processed image. These values are permanent\nand appended to the XMP block alongside the dynamic workflow-based tags.\n\nYou can check the checkboxes below to auto-generate the file creation date,\na camera model identifier, or the raw prompt text as description.",
        "btn_custom_fields": "Configure Global Metadata...",
        "lbl_presets": "💾 Preset Management",
        "btn_save_preset": "Save Preset",
        "btn_delete_preset": "Delete Preset",
        "chk_ui_show_details": "Show details in file list",
        "chk_ui_show_listbox_warnings": "Show warnings for missing/few metadata details in file list",
        "lbl_details_config_header": "Visible details & order:",
        "listbox_model_title": "Checkpoints (Models)",
        "listbox_loras_title": "LoRAs",
        "listbox_resolution_title": "Resolution Category",
        "listbox_date_title": "Creation Date",
        "listbox_resolution": "Res",
        "listbox_date": "Date",
        "lbl_sec_layout_list": "📁 File List & View Settings",
        "lbl_sec_layout_list_tooltip": "Configure how files, previews, and metadata are presented in the main window.",
        "lbl_sec_layout_preview": "🏷 XMP Preview Settings",
        "lbl_sec_layout_preview_tooltip": "Configure the live XMP tag preview and extra metadata visibility.",
        "lbl_sec_layout_appearance": "🎨 Appearance Settings",
        "lbl_sec_layout_appearance_tooltip": "Customize font sizes, display thumbnail dimensions, and color themes.",
        "lbl_sec_language": "🌐 Language Settings",
        "lbl_sec_language_tooltip": "Choose the language of the user interface (English or German).",
        "chk_ui_preview_extra_meta": "Show extra XMP/EXIF metadata (creator, copyright, etc.) in preview",
        "lbl_ui_text_size": "Text size file list:",
        "lbl_ui_preview_text_size": "Text size XMP preview:",
        "lbl_ui_thumb_size": "Preview Image Size:",
        "lbl_ui_language": "Interface Language:",
        "lbl_status_ready": "Ready. Please select a folder.",
        "lbl_preview_title": "🏷 Live XMP Tag Preview",
        "lbl_info_filename": "📁 File: None selected",
        "lbl_info_resolution": "📐 Resolution: -",
        "lbl_info_date": "📅 Date: -",
        "lbl_info_models": "🧠 Models: -",
        "lbl_info_loras": "⚡ Active LoRAs: -",
        "lbl_info_sampler": "⚙ Sampler / Scheduler: -",
        "status_badge_no_images": "ℹ STATUS: NO IMAGES",
        "status_badge_untagged": "ℹ STATUS: NOT YET TAGGED (Ready)",
        "status_badge_tagged": "⚠ STATUS: ALREADY TAGGED (🔍 Details)",
        "status_badge_tooltip": "Status of the selected image",
        "btn_select_all": "Select All",
        "btn_deselect_all": "Deselect All",
        "chk_reset_tags": "🗑 Delete XMP tags",
        "chk_reset_tags_tooltip": "Delete all XMP tags completely (Reset mode for tag cleanup).",
        "chk_overwrite_tags_ui": "🧹 Overwrite XMP tags",
        "chk_overwrite_tags_tooltip": "Overwrite existing tags (instead of appending).\nDeletes all old XMP tags from the image and writes ONLY the newly captured tags.",
        "btn_custom_meta_ui": "✍ Custom Metadata...",
        "btn_custom_meta_tooltip": "Opens a window to define custom metadata (Creator, Copyright, Camera Make, Software, User Comment).",
        "lbl_thumb_tooltip": "Click to open the image in standard viewer",
        "btn_process": "⚡ Apply XMP tags",
        "btn_process_reset": "🗑 Remove XMP tags",
        "btn_process_remove_count": "🗑 Remove XMP tags from {count} image(s)",
        "btn_process_remove_none": "🗑 No images selected",
        "btn_process_apply_count": "⚡ Apply XMP tags to {count} image(s)",
        "btn_process_apply_none": "⚡ No images selected",
        "lbl_status_aborted": "Aborted! {success} of {total} images processed.",
        "lbl_status_reset_done": "Finished! {success} of {total} images cleaned of XMP tags.",
        "lbl_status_process_done": "Finished! {success} of {total} images successfully processed.",
        "msg_title_aborted": "Aborted",
        "msg_aborted": "Processing aborted!\n\n{success} of {total} images successfully processed.\n(Time elapsed: {time_str})",
        "msg_title_reset_done": "Tag Reset Completed",
        "msg_reset_done": "XMP tag reset completed!\n{success} of {total} images successfully cleaned of tags.\n\nStar ratings were preserved.\n(Time elapsed: {time_str})",
        "msg_title_success": "Success",
        "msg_success": "XMP tagging completed!\n{success} of {total} images successfully tagged.\n\nYou can now load/refresh the images in digiKam.\n(Time elapsed: {time_str})",
        "msg_title_preset_loaded": "Preset Loaded",
        "msg_preset_loaded": "Preset '{name}' was successfully applied.",
        "msg_title_preset_saved": "Success",
        "msg_preset_saved": "Preset '{name}' was successfully saved.",
        "msg_title_preset_error": "Error",
        "msg_preset_error": "Preset could not be saved.",
        "msg_title_preset_updated": "Success",
        "msg_preset_updated": "Preset '{name}' was successfully updated.",
        "msg_preset_update_error": "Preset '{name}' could not be updated.",
        "msg_title_default_updated": "Success",
        "msg_default_updated": "Standard preset (Default) was successfully updated.",
        "msg_default_update_error": "Standard preset could not be updated.",
        "msg_title_preset_delete_confirm": "Delete Preset",
        "msg_preset_delete_confirm": "Do you really want to delete preset '{name}'?",
        "msg_title_preset_deleted": "Deleted",
        "msg_preset_deleted": "Preset '{name}' was deleted.",
        "msg_preset_delete_default_warning": "The standard preset cannot be deleted.",
        "msg_title_delete_image": "Delete Image",
        "msg_delete_image": "Do you really want to move the image \"{name}\" to the Recycle Bin?",
        "msg_delete_image_error": "The image \"{name}\" could not be deleted.\nIt might be open or locked in another application.",
        "msg_title_scan_error": "Error",
        "msg_scan_error": "Please specify a valid folder path.",
        "msg_title_warning": "Note",
        "msg_no_scanned_files": "No processable ComfyUI PNG files found. Please scan a folder first.",
        "msg_no_checked_files": "No images selected for processing. Please check at least one image.",
        "msg_reset_tags_warn": "WARNING: XMP Tag Reset",
        "msg_reset_tags_body": "Do you really want to remove ALL XMP tags from {count} selected image(s)?\n\nStar ratings and creation dates will be preserved.",
        "msg_process_confirm": "Confirmation",
        "msg_process_body": "Do you want to apply XMP tags to {count} selected images?",
        "dialog_custom_metadata_title": "Write Global Metadata Values",
        "dialog_custom_metadata_creator": "Creator / Author (dc:creator):",
        "dialog_custom_metadata_copyright": "Copyright Notice (dc:rights):",
        "dialog_custom_metadata_camera_make": "Camera Maker (tiff:Make):",
        "dialog_custom_metadata_software": "Software / Generator (xmp:CreatorTool):",
        "dialog_custom_metadata_comment": "Comment (exif:UserComment):",
        "dialog_custom_metadata_save": "Apply & Save",
        "dialog_custom_metadata_cancel": "Cancel",
        "msg_error_image_open": "Image could not be opened:\n{error}",
        "msg_error_stopwords_open": "The fill-words file could not be opened:\n{error}",
        "msg_error_adjectives_open": "The adjectives file could not be opened:\n{error}",
        "msg_error_shortwords_open": "The short-words exceptions file could not be opened:\n{error}",
        "msg_error_whitelist_open": "The whitelist file could not be opened:\n{error}",
        "msg_error_blacklist_open": "The blacklist file could not be opened:\n{error}",
        "lbl_scan_summary_count": "{total} images | {xmp} with XMP tags{warn_str}",
        "summary_warning": "warning",
        "summary_warnings": "warnings",
        "lbl_checked_count_status": "{checked} of {total} selected",
        "original_prompt_header": "Original Prompt:",
        "original_prompt_warning_none": "⚠ NO PROMPT TAGS FOUND (Check workflow keys or adjust filters)",
        "original_prompt_warning_few": "⚠ FEW PROMPT TAGS FOUND (Under 3 words)",
        "dialog_existing_metadata_title": "Existing Metadata of: {filename}",
        "dialog_existing_metadata_xmp_tags": "🏷 EXISTING XMP KEYWORDS (TAGS):",
        "dialog_existing_metadata_xmp_fields": "ℹ OTHER XMP METADATA FIELDS:",
        "dialog_existing_metadata_no_xmp_tags": "  [ No XMP tags present ]",
        "dialog_existing_metadata_no_xmp_fields": "  [ No other XMP metadata fields present ]",
        "dialog_existing_metadata_exif_title": "📷 BINARY EXIF METADATA (CAMERA DETAILS):",
        "dialog_existing_metadata_no_exif": "  [ No binary EXIF data present ]",
        "dialog_existing_metadata_subtitle": "Found XMP and EXIF entries in the file:",
        "dialog_custom_metadata_header": "✍ Configure Custom Metadata Fields",
        "dialog_custom_metadata_desc": "Note: Only filled fields will be written to the images.",
        "dialog_custom_metadata_creator_label": "Creator / Author:",
        "dialog_custom_metadata_copyright_label": "Copyright Notice:",
        "dialog_custom_metadata_camera_make_label": "Camera Maker:",
        "dialog_custom_metadata_software_label": "Software / Generator:",
        "dialog_custom_metadata_comment_label": "Comment (UserComment):",
        "btn_close": "Close",
        "lbl_thumbnail_placeholder": "[Thumbnail]",
        "lbl_preview_title_formatted": "🏷 Live XMP Preview ({current}/{total}): {filename}",
        "status_badge_tooltip_tagged": "ℹ {count} existing XMP tags in image{sample}.\nClick to show all metadata details.",
        "status_badge_tooltip_untagged": "Image contains no XMP tags yet.",
        "lbl_info_filename_val": "📁 File: {filename}",
        "lbl_info_resolution_val": "📐 Resolution: {w} × {h} px ({mp} MP)",
        "lbl_info_date_val": "📅 Date: {date}",
        "lbl_info_models_val": "🧠 Models: {models}",
        "lbl_info_loras_val": "⚡ Active LoRAs: {loras}",
        "lbl_info_sampler_val": "⚙ Sampler / Scheduler: {samplers} / {schedulers}",
        "val_none": "None",
        "preview_reset_header": "🗑 RESET MODE ACTIVE: The following XMP tags will be deleted (Star ratings will remain protected):\n\n",
        "preview_no_tags_to_reset": "  [ No existing XMP tags present to delete ]\n",
        "preview_hierarchical_header": "Hierarchical Tags (DigiKam Tree - lr:hierarchicalSubject):\n\n",
        "preview_flat_header": "\nFlat Tags (dc:subject):\n",
        "preview_overwrite_header": "\nTags to be removed (overwritten):\n",
        "preview_warn_no_prompts_header": "\n⚠ NOTE: No prompt tags captured!\n",
        "preview_warn_no_prompts_body": "  (Possible reasons: Prompt is running text without commas,\n  wrong Node ID/field name in settings, or\n  no matching positive prompt node in workflow.)\n",
        "preview_warn_few_prompts_header": "\n⚠ NOTE: Few prompt tags captured!\n",
        "preview_warn_few_prompts_body": "  (Possible reason: Prompt might be running text.\n  Use 'Word-based tagging' option if needed.)\n",
        "preview_original_prompt_header": "\nOriginal Prompt:\n",
        "preview_exif_header": "\n[Existing Binary EXIF Metadata]:\n",
        "btn_save_preset_as": "Save As...",
        "lbl_prompt_keys_desc": "Detected prompt field names or Node IDs (one key/ID per line):",
        "tab_settings": "⚙ Settings & Tag Rules",
        "btn_save_default": "Set Default",
        "tab_layout": "🎨 Layout & Design",
        "tab_analyzer": "🔍 Workflow Analyzer",
        "tab_help": "❓ Help & About",
        "help_seg_getting_started": "🚀 Getting Started",
        "help_seg_tagging_rules": "🏷️ Tagging Rules",
        "help_seg_shortcuts": "⌨️ Shortcuts",
        "help_seg_about": "ℹ️ About",
        "help_about_title": "ComfyUI XMP Tagger",
        "help_about_version": "Version 1.0.0 (Milestone 14) by bitcursher-design",
        "help_about_desc": "A high-performance desktop utility designed to automatically extract ComfyUI workflows and prompts from PNG files and embed them as hierarchical XMP tags for DigiKam and other photo management suites.",
        "help_about_github": "GitHub Repository:",
        "help_btn_changelog": "View Changelog...",
        "help_title_changelog": "Changelog / Version History",
        "help_gs_intro_title": "💡 Background & Purpose",
        "help_gs_intro_desc": "AI image generators like ComfyUI embed detailed generation parameters (prompts, models, samplers) inside the PNG file. However, standard photo managers cannot read or index this internal data. This app extracts that metadata and embeds it as standard XMP tags (both flat and hierarchical). Once processed, you can import your images into software like DigiKam or Adobe Lightroom to instantly search, filter, and organize thousands of generated images by the exact model, active LoRAs, samplers, or prompts used to create them.",
        "help_gs_step1_title": "1. Select Directory",
        "help_gs_step1_desc": "Choose your target folder containing ComfyUI PNG files. If your collection is split into subdirectories, toggle 'Recursive' to automatically traverse all subfolders. The app only scans the directory and doesn't modify anything yet. Ideal for preparing large image libraries before processing.",
        "help_gs_step2_title": "2. Scan and Verify",
        "help_gs_step2_desc": "Click 'Scan Folder' to load the PNG files. Click on any file or navigate the list using your arrow keys. On the left side of the dashboard, you will immediately see a structured summary of parsed metadata (Checkpoints, active LoRAs, Sampler/Scheduler, Resolution, and Creation Date) alongside status indicators (tagged/untagged/warnings). Checkboxes allow selective batch tagging.",
        "help_gs_step3_title": "3. Live Preview",
        "help_gs_step3_desc": "Look at the right side of the dashboard: the 'XMP Preview' box displays the exact XML tags and metadata that will be written. Green tags represent new tags extracted from the prompt/models, Gray tags represent tags already present in the image (which will be kept), and Red tags represent tags that will be deleted (if 'Overwrite' or 'Reset' mode is active). If tags are empty, you will receive a yellow/red warning indicating that your prompt keys in Settings might need adjustments.",
        "help_gs_step4_title": "4. Apply Changes",
        "help_gs_step4_desc": "Click 'Apply XMP Tags' to write the metadata. In 'Embed' mode, the app directly edits the PNG byte structure in ~30 milliseconds per image without re-encoding pixels, maintaining full image quality and keeping original ComfyUI metadata intact. In 'Sidecar' mode, it creates separate .xmp files. Once done, open your image manager (e.g. DigiKam) and select 'Re-read Metadata from File' to load the hierarchical tags!",
        "help_tr_std_title": "Standard Tagging Mode",
        "help_tr_std_desc": "Splits positive prompt text blocks strictly by commas and cleans up weights/brackets. Ideal for standard tag-based workflows.",
        "help_tr_word_title": "Word-Based Tagging Mode",
        "help_tr_word_desc": "Splits prompts into single words. Filters out generic stop words, ignores short words unless whitelisted, and merges adjectives with subsequent nouns.",
        "help_tr_list_title": "Whitelist & Blacklist",
        "help_tr_list_desc": "Use the Whitelist to restrict written tags to a specific dictionary. Use the Blacklist/Stopwords to filter out quality prompts or specific tags globally.",
        "help_tr_meta_title": "Custom Metadata & EXIF",
        "help_tr_meta_desc": "Configure global values like Creator, Copyright, and Software, or map model names, samplers, and schedulers to standard EXIF fields.",
        "help_sc_del_title": "Delete / Entf",
        "help_sc_del_desc": "Move the currently highlighted image file directly to the Recycle Bin.",
        "help_sc_nav_title": "Up / Down Arrow",
        "help_sc_nav_desc": "Navigate through the file list and instantly load their XMP preview.",
        "help_sc_space_title": "Spacebar / Leertaste",
        "help_sc_space_desc": "Toggle the selection checkbox state of the currently highlighted image.",
        "help_sc_f5_title": "F5 key",
        "help_sc_f5_desc": "Refresh and re-scan the currently selected directory.",
        "btn_select_sample": "Select Sample Image...",
        "lbl_sample_file_placeholder": "No image selected",
        "lbl_sample_file_val": "File: {filename}",
        "lbl_analyzer_instruction": "This tool helps you find where positive prompts are stored in your ComfyUI workflows:\n\n1. Select a ComfyUI-generated PNG file using the button above.\n2. The analyzer scans the metadata to identify potential prompt text fields (skipping file paths and negative prompts).\n3. Click the shortcut buttons next to any detected candidate to automatically add its Node ID, Input Key, or Custom Node Name to your settings. This saves you from having to search through JSON files in text editors or reloading workflows in ComfyUI!",
        "lbl_analyzer_no_meta": "No ComfyUI metadata found in this image.",
        "lbl_analyzer_intro": "The following text fields were identified as potential positive prompt candidates. Click the buttons next to them to directly add their node IDs or custom names to your Settings.",
        "btn_add_node_id": "+ Add Node ID '{node_id}'",
        "btn_add_node_title": "+ Add Node Name '{title}'",
        "msg_key_added": "Key '{key}' added to Custom Prompt Keys!",
        "msg_key_already_exists": "Key '{key}' already exists in Custom Prompt Keys.",
        "lbl_cand_source": "Source: {source}",
        "lbl_cand_node": "Node: {title} (ID: {node_id})",
        "btn_load": "Load",
        "lbl_files_found": "🖼 Found PNG Files:",
        "tab_process": "📷 Processing & Preview",
        "lbl_status_scan_complete": "Scan complete: {valid} of {total} images with ComfyUI metadata listed.",
        "lbl_status_scan_cancelled": "Scan cancelled! {valid} of {total} PNGs loaded.",
        "lbl_status_no_pngs": "No PNG files found in '{folder}'.",
        "lbl_status_scanning_count": "Scanning {count} PNG files...",
        "lbl_status_scanning_progress": "Scanning PNG files... ({current}/{total})",
        "btn_scan_cancel": "❌ Cancel Scan",
        "btn_scanning": "Scanning...",
        "lbl_status_image_deleted": "Image deleted: {filename}",
        "lbl_status_cancelling": "Cancelling operation...",
        "lbl_status_aborted_summary": "Aborted! {count} of {total} images processed. (Time elapsed: {time})",
        "lbl_status_reset_done_summary": "Done! {count} of {total} images cleaned of XMP tags. (Time elapsed: {time})",
        "lbl_status_success_summary": "Done! {count} of {total} images successfully processed. (Time elapsed: {time})",
        "lbl_status_processing_reset": "Cleaning image {current} of {total}: {filename}",
        "lbl_status_processing_tag": "Processing image {current} of {total}: {filename}",
        "btn_process_cancel": "❌ Cancel processing",
        "btn_cancelling": "⏳ Cancelling...",
        "msg_process_already_tagged": "\n\n⚠ Note: {count} image(s) already contain XMP tags and will be updated.",
        "msg_preset_save_title": "Save Preset",
        "msg_preset_save_prompt": "Enter a name for the new preset:",
        "val_seconds": "{seconds:.1f} sec.",
        "val_minutes_seconds": "{mins} min {secs} sec",
        "listbox_model": "Model",
        "listbox_none_m": "None",
        "listbox_loras": "LoRAs",
        "listbox_none_f": "None",
        "lbl_active_theme": "Active Color Theme:",
        "btn_customize_theme": "🎨 Customize Colors...",
        "dialog_theme_editor_title": "Customize Color Theme",
        "btn_save_theme_as": "Save Theme As...",
        "btn_delete_theme": "Delete Theme",
        "msg_title_theme_saved": "Success",
        "msg_theme_saved": "Theme '{name}' was successfully saved.",
        "msg_theme_error": "Theme could not be saved.",
        "msg_title_theme_error": "Error",
        "msg_title_theme_deleted": "Deleted",
        "msg_theme_deleted": "Theme '{name}' was deleted.",
        "msg_theme_delete_default_warning": "Default themes cannot be deleted.",
        "msg_theme_delete_confirm": "Do you really want to delete theme '{name}'?",
        "msg_title_theme_delete_confirm": "Delete Theme",
        "msg_theme_save_prompt": "Enter a name for the new custom theme:",
        "color_primary_btn": "Primary Button (Background)",
        "color_primary_hover": "Primary Button (Hover)",
        "color_secondary_btn": "Secondary Button / Selection (Background)",
        "color_secondary_hover": "Secondary Button (Hover)",
        "color_danger_btn": "Danger Button / Tagged Badge",
        "color_danger_hover": "Danger Button (Hover)",
        "color_warning_btn": "Warning Button",
        "color_warning_hover": "Warning Button (Hover)",
        "color_neutral_btn": "Neutral Button (Background)",
        "color_neutral_hover": "Neutral Button (Hover)",
        "color_inner_frame_bg": "Inner Frame Background",
        "color_info_link": "Link & Help Icon",
        "color_badge_untagged": "Status Badge: Untagged",
        "color_tag_new": "New Tags Highlight / Checked Box",
        "color_tag_existing": "Existing Tags / Unchecked Box",
        "color_tag_deleted": "Deleted Tags (Preview)",
        "color_tag_warning": "Warning (0 Prompts)",
        "color_tag_low_warning": "Low Warning (<3 Prompts)",
        "color_tag_xmp_prefix": "XMP Tag Prefix [XMP]",
        "color_listbox_details": "Listbox Secondary Details",
        "color_textbox_prompt_body": "Original Prompt Text",
        "color_label_text": "General Label / Text Color",
        "color_listbox_selected_bg": "Listbox Selected Item Background",
        "color_progress_bar": "Progress Bar Color",
        "color_info_date": "Metadata Date Color",
        "color_tag_extra_meta": "Extra XMP/EXIF Metadata Color",
        "preview_extra_metadata_header": "\n[Extra Metadata to be written]:\n"
    },
    "de": {
        "app_title": "ComfyUI XMP Tagger",
        "header_title": "📷 ComfyUI PNG Metadata -> DigiKam XMP Tagger",
        "header_subtitle": "Wandelt ComfyUI Workflows automatisch in hierarchische XMP-Tags um",
        "scan_dir_label": "Verzeichnis:",
        "scan_dir_placeholder": "Wähle einen Ordner mit ComfyUI PNG-Bildern...",
        "btn_browse": "Durchsuchen...",
        "btn_next_folder": "⏭ Nächster Ordner",
        "btn_scan": "Ordner scannen",
        "lbl_sec_categories_prefixes": "📌 Tag-Kategorien & Präfixe",
        "lbl_sec_categories_prefixes_tooltip": "Wähle aus, welche Kategorien aus den ComfyUI-Metadaten erfasst werden sollen.\nDie Präfixe legen die Ordnerstruktur in DigiKam fest (z. B. 'Model/juggernaut').",
        "lbl_prefix_short": "Präfix:",
        "tab_tagger_options": "Tagger-Optionen",
        "tab_metadata_selection": "Metadaten-Auswahl",
        "tab_layout_design": "Layout & Design",
        "lbl_categories": "Erfasste Kategorien",
        "chk_include_models": "Modellnamen (Checkpoints) erfassen",
        "chk_include_loras": "LoRA-Namen erfassen",
        "chk_include_samplers": "Sampler / Scheduler erfassen",
        "chk_include_prompts": "Prompt-Keywords erfassen (Fließtext)",
        "chk_write_flat_dc": "Flache Stichwörter schreiben (dc:subject)",
        "chk_ignore_inactive_nodes": "Inaktive/stumme Nodes ignorieren",
        "chk_ignore_numeric_tags": "Reine Zahlen ausschließen (z. B. seed, cfg)",
        "chk_lowercase_prompt_tags": "Prompt-Tags auf Kleinschreibung normalisieren (vermeidet Duplikate wie \"Portrait\" / \"portrait\")",
        "chk_recursive_scan": "Rekursiv",
        "chk_recursive_scan_tooltip": "Wenn aktiv, werden PNG-Bilder auch in allen Unterordnern des ausgewählten Verzeichnisses gesucht und eingelesen.",
        "lbl_sec_resolution_tiers": "📐 Megapixel Stufen (Auflösungs-Tags)",
        "lbl_sec_resolution_tiers_tooltip": "Generiert Tags basierend auf der Megapixel-Größe des Bildes.\nNützlich um Previews, Standardbilder und hochskalierte Bilder (Upscale) zu kennzeichnen.",
        "lbl_res_tier1_desc": "Stufe 1 (Preview): <",
        "lbl_res_tier2_desc": "Stufe 2 (Standard): <",
        "lbl_res_tier3_desc": "Stufe 3 (Upscale): >=",
        "lbl_res_tier2_mp_arrow": "Stufe 2 MP ->",
        "lbl_sec_active_lora_filter": "🎯 Active LoRA & Node Filter",
        "lbl_sec_active_lora_filter_tooltip": "Nodes, die in ComfyUI stummgeschaltet oder umgangen wurden (Muted/Bypassed),\nkönnen ignoriert werden. LoRAs unter der Mindeststärke werden nicht erfasst.",
        "chk_overwrite_existing_tags": "XMP-Tags überschreiben (Statt anhängen)",
        "chk_word_based_tagging": "Prompts in Einzelwörter zerlegen (Wort-basiert)",
        "lbl_sec_whitelist": "✅ Positiv-Liste (Whitelist)",
        "lbl_sec_whitelist_tooltip": "Wenn die Positiv-Liste (Whitelist) aktiv ist, werden ausschließlich Tags erfasst\nund gespeichert, die exakt mit den Einträgen dieser Liste übereinstimmen oder diese\nenthalten. Alle anderen extrahierten Tags werden verworfen.\n\nTrage kommagetrennte Begriffe ein oder bearbeite die Datei 'whitelist.txt'\ndirekt über den Link unten. Ideal zur Einschränkung auf ein festes\nTag-Vokabular (z. B. für DigiKam-Projekte).",
        "lbl_sec_blacklist": "🚫 Stoppwörter (Blacklist)",
        "lbl_sec_blacklist_tooltip": "Globale Filter-Optionen: Begriffe auf diesen Listen werden komplett aus allen ausgelesenen Metadaten (Prompts, Modellen, LoRAs, Samplern etc.) herausgefiltert.\n- Blacklist: Verwirft passende Wörter/Phrasen (kommagetrennt).\n- Reine Zahlen ausschließen: Ignoriert numerische Tags wie Seeds.\n- Kleinschreibung normalisieren: Wandelt Tags in Kleinbuchstaben um, um Duplikate zu vermeiden.\n- Wort-basiertes Tagging (Stoppwörter/Adjektive): Zerlegt Prompts in Einzelwörter und filtert sie mittels Stoppwort-Listen, Adjektiv-Verbindungsregeln oder Mindestlängen.",
        "lbl_edit_stopwords": "📄 Liste der Füllwörter bearbeiten (stopwords.txt)",
        "lbl_edit_adjectives": "📄 Liste der Adjektive bearbeiten (adjectives.txt)",
        "lbl_edit_short_words": "📄 Liste der Kurzwort-Ausnahmen bearbeiten (short_words.txt)",
        "lbl_edit_whitelist": "📄 Whitelist-Datei bearbeiten (whitelist.txt)",
        "lbl_edit_blacklist": "📄 Blacklist-Datei bearbeiten (blacklist.txt)",
        "lbl_resolution_settings": "📐 Bildgrößen- & Auflösungs-Tags",
        "chk_include_resolution": "Auflösungs-Tags generieren (MP-Stufen)",
        "lbl_res_prefix": "Präfix für Auflösungs-Tag:",
        "lbl_res_tier1": "Stufe 1 (z.B. Preview) MP-Grenze:",
        "lbl_res_tier1_name": "Bezeichnung:",
        "lbl_res_tier2": "Stufe 2 (z.B. Standard) MP-Grenze:",
        "lbl_res_tier3_name": "Stufe 3 (z.B. Upscale) Bezeichnung:",
        "lbl_tag_prefixes": "🏷 Präfixe in der hierarchischen Struktur",
        "lbl_prefix_model": "Modell-Präfix:",
        "lbl_prefix_lora": "LoRA-Präfix:",
        "lbl_prefix_sampler": "Sampler-Präfix:",
        "lbl_prefix_prompt": "Prompt-Präfix:",
        "lbl_min_lora_strength": "Mindeststärke für LoRA-Erfassung:",
        "lbl_max_tag_length": "Maximale Stichwortlänge (Zeichen):",
        "lbl_whitelist_settings": "✅ Positiv-Liste (Ausschließlich diese Tags erfassen)",
        "chk_use_whitelist": "Nur Keywords aus der Whitelist zulassen",
        "lbl_whitelist_tags": "Stichwörter (Komma-getrennt):",
        "lbl_blacklist_settings": "🚫 Negativ-Liste (Diese Stichwörter ignorieren)",
        "lbl_blacklist_tags": "Stichwörter (Komma-getrennt):",
        "lbl_custom_prompt_keys": "🔑 Eigene Prompt-Feldnamen (Workflow-Keys)",
        "lbl_sec_custom_prompt_keys": "🔑 Eigene Prompt-Feldnamen (Workflow-Keys)",
        "lbl_sec_custom_prompt_keys_tooltip": "Eigene Prompt-Feldnamen ermöglichen das Auslesen von Prompts aus\nbenutzerdefinierten ComfyUI-Nodes (wie speziellen Textloadern),\nsatt nur aus Standard-KSamplern. Trage einen Schlüssel pro Zeile ein.\nDie App durchsucht die Widgets und Inputs des ComfyUI-Workflows nach\ndiesen Bezeichnungen und extrahiert deren Textinhalte.",
        "lbl_storage_mode": "💾 Speichermodus",
        "lbl_sec_storage_mode": "💾 Speicher- & Prozess-Optionen",
        "lbl_sec_storage_mode_tooltip": "Konfiguriere Speicherziele für Metadaten sowie Bestätigungsdialoge beim Taggen.",
        "chk_show_tagging_confirm": "Bestätigungsdialog vor dem Schreiben von XMP-Tags anzeigen",
        "chk_show_tagging_confirm_tooltip": "Wenn aktiv, wird vor dem eigentlichen Schreibvorgang noch einmal nach einer Bestätigung gefragt.",
        "lbl_storage_mode_desc": "Wie sollen die XMP-Metadaten gespeichert werden?",
        "rad_storage_embed": "Direkt in PNG-Datei einbetten (Empfohlen)",
        "rad_storage_sidecar": "Als XMP-Sidecar-Datei schreiben (.png.xmp)",
        "chk_write_created_date": "Erstellungsdatum schreiben (xmp:CreateDate)",
        "chk_write_camera_model": "Kameramodell schreiben (tiff:Model)",
        "chk_write_description": "Beschreibung schreiben (dc:description)",
        "lbl_custom_fields": "✍ Globale Metadaten-Werte",
        "lbl_sec_extra_meta": "✍ Globale Metadaten-Werte",
        "lbl_sec_extra_meta_tooltip": "Konfiguriere feste Metadatenfelder, die zusammen mit den Tags in jedes Bild\ngeschrieben werden. Diese Werte sind dauerhaft und werden neben den dynamischen\nWorkflow-basierten Tags in den XMP-Block geschrieben.\n\nAktiviere die Checkboxen unten, um automatisch das Erstellungsdatum,\nein Kameramodell oder den rohen Prompt als Bildbeschreibung einzutragen.",
        "btn_custom_fields": "Globale Metadaten-Werte konfigurieren...",
        "lbl_presets": "💾 Preset-Verwaltung",
        "btn_save_preset": "Preset speichern",
        "btn_delete_preset": "Preset löschen",
        "chk_ui_show_details": "Details in Dateiliste anzeigen",
        "chk_ui_show_listbox_warnings": "Warnungen bei fehlenden Metadaten in Dateiliste anzeigen",
        "lbl_details_config_header": "Sichtbare Details & Reihenfolge:",
        "listbox_model_title": "Modelle (Checkpoints)",
        "listbox_loras_title": "LoRAs",
        "listbox_resolution_title": "Auflösungs-Kategorie",
        "listbox_date_title": "Erstellungsdatum",
        "listbox_resolution": "Auflösung",
        "listbox_date": "Datum",
        "lbl_sec_layout_list": "📁 Dateiliste & Ansichts-Einstellungen",
        "lbl_sec_layout_list_tooltip": "Konfiguriere, wie Dateien, Vorschauen und Metadaten im Hauptfenster dargestellt werden.",
        "lbl_sec_layout_preview": "🏷 XMP-Vorschau-Einstellungen",
        "lbl_sec_layout_preview_tooltip": "Konfiguriere die Live-XMP-Tag-Vorschau und die Sichtbarkeit zusätzlicher Metadaten.",
        "lbl_sec_layout_appearance": "🎨 Erscheinungsbild-Einstellungen",
        "lbl_sec_layout_appearance_tooltip": "Passe Schriftgrößen, Vorschaubild-Größen und Farb-Themes an.",
        "lbl_sec_language": "🌐 Spracheinstellungen",
        "lbl_sec_language_tooltip": "Wähle die Sprache der Benutzeroberfläche aus (Deutsch oder Englisch).",
        "chk_ui_preview_extra_meta": "Zusätzliche XMP/EXIF-Metadaten (Autor, Copyright, etc.) in Vorschau anzeigen",
        "lbl_ui_text_size": "Textgröße Dateiliste:",
        "lbl_ui_preview_text_size": "Textgröße XMP-Vorschau:",
        "lbl_ui_thumb_size": "Vorschau-Bildgröße:",
        "lbl_ui_language": "Anzeigesprache (Language):",
        "lbl_status_ready": "Bereit. Bitte wähle einen Ordner aus.",
        "lbl_preview_title": "🏷 Live XMP Tag Vorschau",
        "lbl_info_filename": "📁 Datei: Keine ausgewählt",
        "lbl_info_resolution": "📐 Auflösung: -",
        "lbl_info_date": "📅 Datum: -",
        "lbl_info_models": "🧠 Modelle: -",
        "lbl_info_loras": "⚡ Aktive LoRAs: -",
        "lbl_info_sampler": "⚙ Sampler / Scheduler: -",
        "status_badge_no_images": "ℹ STATUS: KEINE BILDER",
        "status_badge_untagged": "ℹ STATUS: NOCH NICHT GETAGGT (Bereit)",
        "status_badge_tagged": "⚠ STATUS: BEREITS GETAGGT (🔍 Details)",
        "status_badge_tooltip": "Status des gewählten Bildes",
        "btn_select_all": "Alle auswählen",
        "btn_deselect_all": "Auswahl aufheben",
        "chk_reset_tags": "🗑 XMP-Tags löschen",
        "chk_reset_tags_tooltip": "XMP-Tags restlos löschen (Reset-Modus zur Tag-Bereinigung).",
        "chk_overwrite_tags_ui": "🧹 XMP-Tags überschreiben",
        "chk_overwrite_tags_tooltip": "Vorhandene Tags überschreiben (statt anhängen).\nLöscht alle alten XMP-Tags aus dem Bild und schreibt NUR die neu erfassten Tags.",
        "btn_custom_meta_ui": "✍ Custom Metadaten...",
        "btn_custom_meta_tooltip": "Öffnet ein Fenster, um benutzerdefinierte Metadaten (Ersteller, Copyright, Kamerahersteller, Software, Kommentar) festzulegen.",
        "lbl_thumb_tooltip": "Klicken, um das Bild im Standard-Betrachter zu öffnen",
        "btn_process": "⚡ XMP-Tags anwenden",
        "btn_process_reset": "🗑 XMP-Tags entfernen",
        "btn_process_remove_count": "🗑 XMP-Tags aus {count} Bild(ern) entfernen",
        "btn_process_remove_none": "🗑 Keine Bilder ausgewählt",
        "btn_process_apply_count": "⚡ XMP-Tags auf {count} Bild(er) anwenden",
        "btn_process_apply_none": "⚡ Keine Bilder ausgewählt",
        "lbl_status_aborted": "Abgebrochen! {success} von {total} Bildern verarbeitet.",
        "lbl_status_reset_done": "Fertig! {success} von {total} Bildern von XMP-Tags bereinigt.",
        "lbl_status_process_done": "Fertig! {success} von {total} Bildern erfolgreich verarbeitet.",
        "msg_title_aborted": "Abgebrochen",
        "msg_aborted": "Verarbeitung abgebrochen!\n\n{success} von {total} Bildern wurden erfolgreich verarbeitet.\n(Benötigte Zeit: {time_str})",
        "msg_title_reset_done": "Tag-Reset abgeschlossen",
        "msg_reset_done": "XMP Tag-Reset abgeschlossen!\n{success} von {total} Bildern erfolgreich von Tags bereinigt.\n\nSterne-Bewertungen blieben erhalten.\n(Benötigte Zeit: {time_str})",
        "msg_title_success": "Erfolg",
        "msg_success": "XMP Tagging abgeschlossen!\n{success} von {total} Bildern erfolgreich getaggt.\n\nDu kannst die Bilder nun in DigiKam laden/aktualisieren.\n(Benötigte Zeit: {time_str})",
        "msg_title_preset_loaded": "Preset geladen",
        "msg_preset_loaded": "Preset '{name}' wurde erfolgreich angewendet.",
        "msg_title_preset_saved": "Erfolg",
        "msg_preset_saved": "Preset '{name}' wurde erfolgreich gespeichert.",
        "msg_title_preset_error": "Fehler",
        "msg_preset_error": "Preset konnte nicht gespeichert werden.",
        "msg_title_preset_updated": "Erfolg",
        "msg_preset_updated": "Preset '{name}' wurde erfolgreich aktualisiert.",
        "msg_preset_update_error": "Preset '{name}' konnte nicht aktualisiert werden.",
        "msg_title_default_updated": "Erfolg",
        "msg_default_updated": "Standard-Preset (Default) wurde erfolgreich aktualisiert.",
        "msg_default_update_error": "Standard-Preset konnte nicht aktualisiert werden.",
        "msg_title_preset_delete_confirm": "Preset löschen",
        "msg_preset_delete_confirm": "Möchtest du das Preset '{name}' wirklich löschen?",
        "msg_title_preset_deleted": "Gelöscht",
        "msg_preset_deleted": "Preset '{name}' wurde gelöscht.",
        "msg_preset_delete_default_warning": "Das Standard-Preset kann nicht gelöscht werden.",
        "msg_title_delete_image": "Bild löschen",
        "msg_delete_image": "Möchtest du das Bild \"{name}\" wirklich in den Papierkorb verschieben?",
        "msg_delete_image_error": "Das Bild \"{name}\" konnte nicht gelöscht werden.\nEventuell ist es in einem anderen Programm geöffnet oder gesperrt.",
        "msg_title_scan_error": "Fehler",
        "msg_scan_error": "Bitte gib einen gültigen Ordnerpfad an.",
        "msg_title_warning": "Hinweis",
        "msg_no_scanned_files": "Keine verarbeitbaren ComfyUI PNG-Dateien vorhanden. Scanne zuerst einen Ordner.",
        "msg_no_checked_files": "Keine Bilder für die Verarbeitung ausgewählt. Hake mindestens ein Bild an.",
        "msg_reset_tags_warn": "WARNUNG: XMP Tag-Reset",
        "msg_reset_tags_body": "Möchtest du wirklich ALLE XMP-Tags aus {count} ausgewählten Bild(ern) entfernen?\n\nSterne-Bewertungen und Erstellungsdaten bleiben erhalten.",
        "msg_process_confirm": "Bestätigung",
        "msg_process_body": "Möchtest du XMP-Tags in {count} ausgewählten Bildern anwenden?",
        "dialog_custom_metadata_title": "Globale Metadaten Werte schreiben",
        "dialog_custom_metadata_creator": "Ersteller / Autor (dc:creator):",
        "dialog_custom_metadata_copyright": "Copyright Hinweis (dc:rights):",
        "dialog_custom_metadata_camera_make": "Kamera-Hersteller (tiff:Make):",
        "dialog_custom_metadata_software": "Software / Generator (xmp:CreatorTool):",
        "dialog_custom_metadata_comment": "Kommentar (exif:UserComment):",
        "dialog_custom_metadata_save": "Übernehmen & Speichern",
        "dialog_custom_metadata_cancel": "Abbrechen",
        "msg_error_image_open": "Bild konnte nicht geöffnet werden:\n{error}",
        "msg_error_stopwords_open": "Die Füllwort-Datei konnte nicht geöffnet werden:\n{error}",
        "msg_error_adjectives_open": "Die Adjektiv-Datei konnte nicht geöffnet werden:\n{error}",
        "msg_error_shortwords_open": "Die Kurzwort-Ausnahme-Datei konnte nicht geöffnet werden:\n{error}",
        "msg_error_whitelist_open": "Die Whitelist-Datei konnte nicht geöffnet werden:\n{error}",
        "msg_error_blacklist_open": "Die Blacklist-Datei konnte nicht geöffnet werden:\n{error}",
        "lbl_scan_summary_count": "{total} Bilder | {xmp} mit XMP-Tags{warn_str}",
        "summary_warning": "Warnung",
        "summary_warnings": "Warnungen",
        "lbl_checked_count_status": "{checked} von {total} ausgewählt",
        "original_prompt_header": "Originaler Prompt:",
        "original_prompt_warning_none": "⚠ KEINE PROMPT-TAGS GEFUNDEN (Workflow-Keys prüfen oder Filter anpassen)",
        "original_prompt_warning_few": "⚠ WENIGE PROMPT-TAGS GEFUNDEN (Unter 3 Wörter)",
        "dialog_existing_metadata_title": "Vorhandene Metadaten von: {filename}",
        "dialog_existing_metadata_xmp_tags": "🏷 BESTEHENDE XMP-SCHLAGWÖRTER (TAGS):",
        "dialog_existing_metadata_xmp_fields": "ℹ WEITERE XMP METADATEN-FELDER:",
        "dialog_existing_metadata_no_xmp_tags": "  [ Keine XMP-Tags vorhanden ]",
        "dialog_existing_metadata_no_xmp_fields": "  [ Keine weiteren XMP-Metadaten-Felder vorhanden ]",
        "dialog_existing_metadata_exif_title": "📷 BINÄRE EXIF-METADATEN (KAMERA-DETAILS):",
        "dialog_existing_metadata_no_exif": "  [ Keine binären EXIF-Daten vorhanden ]",
        "lbl_thumbnail_placeholder": "[Vorschaubild]",
        "lbl_preview_title_formatted": "🏷 Live XMP Vorschau ({current}/{total}): {filename}",
        "status_badge_tooltip_tagged": "ℹ {count} bestehende XMP-Tags im Bild{sample}.\nKlicken zum Anzeigen aller Metadaten-Details.",
        "status_badge_tooltip_untagged": "Bild enthält noch keine XMP-Tags.",
        "lbl_info_filename_val": "📁 Datei: {filename}",
        "lbl_info_resolution_val": "📐 Auflösung: {w} × {h} px ({mp} MP)",
        "lbl_info_date_val": "📅 Datum: {date}",
        "lbl_info_models_val": "🧠 Modelle: {models}",
        "lbl_info_loras_val": "⚡ Aktive LoRAs: {loras}",
        "lbl_info_sampler_val": "⚙ Sampler / Scheduler: {samplers} / {schedulers}",
        "val_none": "Keine",
        "preview_reset_header": "🗑 RESET-MODUS AKTIV: Folgende XMP-Tags werden gelöscht (Sterne-Bewertungen bleiben geschützt):\n\n",
        "preview_no_tags_to_reset": "  [ Keine bestehenden XMP-Tags zum Löschen vorhanden ]\n",
        "preview_hierarchical_header": "Hierarchische Tags (DigiKam Baum - lr:hierarchicalSubject):\n\n",
        "preview_flat_header": "\nFlache Tags (dc:subject):\n",
        "preview_overwrite_header": "\nZu entfernende (überschriebene) Tags:\n",
        "preview_warn_no_prompts_header": "\n⚠ HINWEIS: Keine Prompt-Tags erfasst!\n",
        "preview_warn_no_prompts_body": "  (Mögliche Ursachen: Prompt ist Fließtext ohne Kommas,\n  falsche Node-ID/Feldname in den Einstellungen oder\n  keine passende positive Prompt-Node im Workflow.)\n",
        "preview_warn_few_prompts_header": "\n⚠ HINWEIS: Wenige Prompt-Tags erfasst!\n",
        "preview_warn_few_prompts_body": "  (Mögliche Ursache: Der Prompt ist ggf. Fließtext.\n  Nutze bei Bedarf die Option 'Wort-basiertes Tagging'.)\n",
        "preview_original_prompt_header": "\nOriginaler Prompt:\n",
        "preview_exif_header": "\n[Vorhandene binäre EXIF-Metadaten]:\n",
        "btn_save_preset_as": "Neu speichern...",
        "lbl_prompt_keys_desc": "Erkannte Prompt-Feldnamen oder Node-IDs (ein Key/ID pro Zeile):",
        "tab_settings": "⚙ Einstellungen & Tag-Regeln",
        "btn_save_default": "Als Standard",
        "tab_layout": "🎨 Layout & Design",
        "tab_analyzer": "🔍 Workflow-Analysator",
        "tab_help": "❓ Hilfe & Info",
        "help_seg_getting_started": "🚀 Erste Schritte",
        "help_seg_tagging_rules": "🏷️ Tag-Regeln",
        "help_seg_shortcuts": "⌨️ Tastenkürzel",
        "help_seg_about": "ℹ️ Info",
        "help_about_title": "ComfyUI XMP Tagger",
        "help_about_version": "Version 1.0.0 (Meilenstein 14) by bitcrusher-design",
        "help_about_desc": "Ein hochperformantes Desktop-Tool zur automatischen Extraktion von ComfyUI-Metadaten aus PNG-Bildern, um diese als hierarchische XMP-Tags für DigiKam und andere Bildverwaltungsprogramme einzubetten.",
        "help_about_github": "GitHub-Repository:",
        "help_btn_changelog": "Changelog anzeigen...",
        "help_title_changelog": "Changelog / Versionsverlauf",
        "help_gs_intro_title": "💡 Hintergrund & Einsatzzweck",
        "help_gs_intro_desc": "KI-Bildgeneratoren wie ComfyUI betten detaillierte Erzeugungsparameter (Prompts, Modelle, Sampler) in PNG-Dateien ein. Normale Bildverwaltungsprogramme können diese internen Daten jedoch nicht lesen oder indizieren. Diese App extrahiert diese Metadaten und wandelt sie in standardisierte XMP-Schlagwörter (sowohl flach als auch hierarchisch) um. Nach der Verarbeitung kannst du deine Bilder in Programmen wie DigiKam oder Adobe Lightroom importieren, um tausende KI-Bilder sofort nach dem verwendeten Modell, den aktiven LoRAs, Samplern oder Prompts zu durchsuchen, zu filtern und zu organisieren.",
        "help_gs_step1_title": "1. Ordner auswählen",
        "help_gs_step1_desc": "Wähle dein Zielverzeichnis aus, das von ComfyUI generierte PNG-Bilder enthält. Wenn deine Sammlung in Unterordner aufgeteilt ist, aktiviere 'Rekursiv scannen', um alle Unterverzeichnisse einzubeziehen. Die App liest die Dateien zunächst nur ein, ohne Änderungen vorzunehmen. Perfekt, um große Bildbibliotheken vorzubereiten.",
        "help_gs_step2_title": "2. Scannen & Prüfen",
        "help_gs_step2_desc": "Klicke auf 'Ordner scannen', um die PNG-Bilder zu laden. Klicke auf ein Bild oder navigiere mit den Pfeiltasten durch die Liste. Links im Dashboard siehst du sofort eine strukturierte Zusammenfassung der ausgelesenen Metadaten (Checkpoints, aktive LoRAs, Sampler/Scheduler, Auflösung und Erstelldatum) sowie den Tagging-Status und Warnungen. Über Kontrollkästchen kannst du Bilder gezielt selektieren.",
        "help_gs_step3_title": "3. Live-Vorschau",
        "help_gs_step3_desc": "Prüfe die rechte Seite des Dashboards: Die 'XMP-Vorschau' zeigt genau, welche XML-Tags und Metadaten in das Bild geschrieben werden. Grüne Tags sind neue Schlagwörter (aus Prompt/Modellen), graue Tags sind bereits im Bild enthalten (und bleiben erhalten), während rote Tags gelöscht werden (falls 'Überschreiben' oder 'Reset' aktiv ist). Wenn keine Tags erfasst werden, warnt dich das System in Gelb/Rot, dass ggf. deine Prompt-Schlüssel in den Einstellungen angepasst werden müssen.",
        "help_gs_step4_title": "4. Anwenden",
        "help_gs_step4_desc": "Klicke auf 'XMP-Tags anwenden', um den Vorgang zu starten. Im Modus 'In PNG einbetten' schreibt die App die Metadaten in nur ca. 30 Millisekunden pro Bild verlustfrei direkt in die Byte-Struktur der PNG-Datei, ohne Pixel neu zu komprimieren. Im Modus 'Sidecar' werden separate .xmp-Dateien erstellt. Öffne danach deine Bildverwaltung (z. B. DigiKam) und wähle 'Metadaten aus Datei neu einlesen', um den hierarchischen Tag-Baum zu laden!",
        "help_tr_std_title": "Standard-Tagging",
        "help_tr_std_desc": "Teilt den positiven Prompt strikt an Kommas auf und bereinigt Gewichte. Ideal für klassische, kommagetrennte Tag-Prompts.",
        "help_tr_word_title": "Wort-basiertes Tagging",
        "help_tr_word_desc": "Zerlegt Prompts in Einzelwörter, filtert Füllwörter (Stopwords) aus, ignoriert Kurzwörter und verschmilzt Adjektive mit Nomen.",
        "help_tr_list_title": "Whitelist & Blacklist",
        "help_tr_list_desc": "Nutze die Whitelist, um geschriebene Tags auf ein festes Vokabular zu beschränken. Die Blacklist filtert unerwünschte Tags global heraus.",
        "help_tr_meta_title": "Metadaten & EXIF",
        "help_tr_meta_desc": "Konfiguriere Urheberrecht, Ersteller oder schreibe Modelle und Sampler direkt in standardisierte EXIF-Felder von DigiKam.",
        "help_sc_del_title": "Entf-Taste (Delete)",
        "help_sc_del_desc": "Verschiebt das aktuell ausgewählte Bild direkt in den Windows-Papierkorb.",
        "help_sc_nav_title": "Pfeiltasten (Hoch / Runter)",
        "help_sc_nav_desc": "Navigiert durch die Dateiliste und lädt die Vorschau des gewählten Bildes.",
        "help_sc_space_title": "Leertaste (Space)",
        "help_sc_space_desc": "Wählt das aktuell markierte Bild in der Dateiliste aus oder hebt die Auswahl auf.",
        "help_sc_f5_title": "F5-Taste",
        "help_sc_f5_desc": "Aktualisiert die Dateiliste und scannt das aktuelle Verzeichnis neu.",
        "btn_select_sample": "Beispielbild auswählen...",
        "lbl_sample_file_placeholder": "Kein Bild ausgewählt",
        "lbl_sample_file_val": "Datei: {filename}",
        "lbl_analyzer_instruction": "Dieses Tool hilft dir herauszufinden, wo positive Prompts in deinen ComfyUI-Workflows gespeichert sind:\n\n1. Wähle oben ein von ComfyUI generiertes PNG-Bild aus.\n2. Der Analysator scannt die Metadaten, um Textfelder zu finden, die wie ein positiver Prompt aussehen (Dateipfade und negative Prompts werden ignoriert).\n3. Klicke einfach auf die Schaltflächen neben den Treffern, um deren Node-ID, Eingabeschlüssel oder benutzerdefinierten Node-Namen direkt in deine Einstellungen zu übernehmen. Das erspart dir das Suchen in JSON-Dateien oder das Neuladen in ComfyUI!",
        "lbl_analyzer_no_meta": "Keine ComfyUI-Metadaten in diesem Bild gefunden.",
        "lbl_analyzer_intro": "Die folgenden Textfelder wurden als mögliche positive Prompts identifiziert. Klicke auf die Schaltflächen, um deren Node-IDs oder Namen direkt in die Einstellungen zu übernehmen.",
        "btn_add_node_id": "+ Node-ID '{node_id}' hinzufügen",
        "btn_add_node_title": "+ Name '{title}' hinzufügen",
        "msg_key_added": "Schlüssel '{key}' wurde zu den eigenen Prompt-Feldnamen hinzugefügt!",
        "msg_key_already_exists": "Schlüssel '{key}' ist bereits vorhanden.",
        "lbl_cand_source": "Quelle: {source}",
        "lbl_cand_node": "Node: {title} (ID: {node_id})",
        "btn_load": "Laden",
        "lbl_files_found": "🖼 Gefundene PNG-Dateien:",
        "tab_process": "📷 Verarbeitung & Vorschau",
        "dialog_existing_metadata_subtitle": "Gefundene XMP- und EXIF-Einträge in der Datei:",
        "dialog_custom_metadata_header": "✍ Custom Metadaten-Felder konfigurieren",
        "dialog_custom_metadata_desc": "Hinweis: Nur befüllte Felder werden in die Bilder geschrieben.",
        "dialog_custom_metadata_creator_label": "Ersteller / Autor:",
        "dialog_custom_metadata_copyright_label": "Urheberrechtsvermerk:",
        "dialog_custom_metadata_camera_make_label": "Kamerahersteller:",
        "dialog_custom_metadata_software_label": "Software / Generator:",
        "dialog_custom_metadata_comment_label": "Kommentar (UserComment):",
        "btn_close": "Schließen",
        "lbl_status_scan_complete": "Scan abgeschlossen: {valid} von {total} Bildern mit ComfyUI-Metadaten aufgelistet.",
        "lbl_status_scan_cancelled": "Scan abgebrochen! {valid} von {total} PNGs geladen.",
        "lbl_status_no_pngs": "Keine PNG-Dateien in '{folder}' gefunden.",
        "lbl_status_scanning_count": "Scanne {count} PNG-Dateien...",
        "lbl_status_scanning_progress": "Scanne PNG-Dateien... ({current}/{total})",
        "btn_scan_cancel": "❌ Scan abbrechen",
        "btn_scanning": "Scanne...",
        "lbl_status_image_deleted": "Bild gelöscht: {filename}",
        "lbl_status_cancelling": "Abbruch wird durchgeführt...",
        "lbl_status_aborted_summary": "Abgebrochen! {count} von {total} Bildern verarbeitet. (Benötigte Zeit: {time})",
        "lbl_status_reset_done_summary": "Fertig! {count} von {total} Bildern von XMP-Tags bereinigt. (Benötigte Zeit: {time})",
        "lbl_status_success_summary": "Fertig! {count} von {total} Bildern erfolgreich verarbeitet. (Benötigte Zeit: {time})",
        "lbl_status_processing_reset": "Bereinige Bild {current} von {total}: {filename}",
        "lbl_status_processing_tag": "Verarbeite Bild {current} von {total}: {filename}",
        "btn_process_cancel": "❌ Verarbeitung abbrechen",
        "btn_cancelling": "⏳ Abbruch...",
        "msg_process_already_tagged": "\n\n⚠ Hinweis: {count} Bild(er) enthalten bereits XMP-Tags und werden aktualisiert.",
        "msg_preset_save_title": "Preset speichern",
        "msg_preset_save_prompt": "Gib einen Namen für das neue Preset ein:",
        "val_seconds": "{seconds:.1f} Sek.",
        "val_minutes_seconds": "{mins} Min. {secs} Sek.",
        "listbox_model": "Model",
        "listbox_none_m": "Keines",
        "listbox_loras": "LoRAs",
        "listbox_none_f": "Keine",
        "lbl_active_theme": "Aktives Farbthema:",
        "btn_customize_theme": "🎨 Farbschema anpassen...",
        "dialog_theme_editor_title": "Farbthema anpassen",
        "btn_save_theme_as": "Thema speichern unter...",
        "btn_delete_theme": "Thema löschen",
        "msg_title_theme_saved": "Erfolg",
        "msg_theme_saved": "Farbthema '{name}' wurde erfolgreich gespeichert.",
        "msg_theme_error": "Farbthema konnte nicht gespeichert werden.",
        "msg_title_theme_error": "Fehler",
        "msg_title_theme_deleted": "Gelöscht",
        "msg_theme_deleted": "Farbthema '{name}' wurde gelöscht.",
        "msg_theme_delete_default_warning": "Standard-Farbthemen können nicht gelöscht werden.",
        "msg_theme_delete_confirm": "Möchtest du das Farbthema '{name}' wirklich löschen?",
        "msg_title_theme_delete_confirm": "Farbthema löschen",
        "msg_theme_save_prompt": "Gib einen Namen für das neue Farbthema ein:",
        "color_primary_btn": "Primäre Schaltfläche (Hintergrund)",
        "color_primary_hover": "Primäre Schaltfläche (Hover)",
        "color_secondary_btn": "Sekundäre Schaltfläche / Selektion (Hintergrund)",
        "color_secondary_hover": "Sekundäre Schaltfläche (Hover)",
        "color_danger_btn": "Gefahrenschaltfläche / Badge bereits getaggt",
        "color_danger_hover": "Gefahrenschaltfläche (Hover)",
        "color_warning_btn": "Warnungschaltfläche",
        "color_warning_hover": "Warnungschaltfläche (Hover)",
        "color_neutral_btn": "Neutrale Schaltfläche (Hintergrund)",
        "color_neutral_hover": "Neutrale Schaltfläche (Hover)",
        "color_inner_frame_bg": "Hintergrund Innenbereich (Textboxen/Details)",
        "color_info_link": "Link- & Info-Symbol",
        "color_badge_untagged": "Status-Badge: Noch nicht getaggt",
        "color_tag_new": "Neue Tags / Checkboxen",
        "color_tag_existing": "Bestehende Tags / Inaktive Checkboxen",
        "color_tag_deleted": "Zu löschende Tags (Vorschau)",
        "color_tag_warning": "Warnungs-Tags (0 Prompts)",
        "color_tag_low_warning": "Geringe Warnung (<3 Prompts)",
        "color_tag_xmp_prefix": "XMP-Präfix [XMP]",
        "color_listbox_details": "Listbox Details",
        "color_textbox_prompt_body": "Originaler Prompt-Text",
        "color_label_text": "Allgemeiner Beschriftungstext / Labels",
        "color_listbox_selected_bg": "Dateilisten-Hintergrund für selektierten Eintrag",
        "color_progress_bar": "Farbe des Fortschrittsbalkens",
        "color_info_date": "Metadaten Datum-Farbe",
        "color_tag_extra_meta": "Zusätzliche Metadaten Vorschau-Farbe",
        "preview_extra_metadata_header": "\n[Zusätzliche Metadaten (zu schreiben)]:\n"
    }
}

class Text:
    _lang = "de"
    
    @classmethod
    def set_lang(cls, lang):
        if lang in LOCALIZATION:
            cls._lang = lang
        else:
            cls._lang = "de"
            
    @classmethod
    def get_lang(cls):
        return cls._lang
        
    @classmethod
    def get(cls, key, **kwargs):
        translations = LOCALIZATION.get(cls._lang, LOCALIZATION["de"])
        template = translations.get(key, LOCALIZATION["de"].get(key, key))
        return template.format(**kwargs) if kwargs else template
